services:
  - type: web
    name: document-processing-pipeline
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python run.py
    plan: starter
    healthCheckPath: /
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SINGLE_RUN_MODE
        value: true
      - key: AUTO_PATCH
        value: true
      - key: AUTO_ADVANCE
        value: false
      - key: USE_BATCH_API
        value: false
      - key: MIN_NRR
        value: 0.92
      - key: MIN_FPR
        value: 0.985
      - key: MIN_SS
        value: 0.90
      - key: MIN_TOKEN_REDUCTION
        value: 20
      - key: MONGODB_URL
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: redis
          property: connectionString
      - key: OPENAI_API_KEY
        sync: false
      - key: OPENAI_MODEL
        value: gpt-4-turbo-preview
      - key: MAX_BATCH_SIZE
        value: 1000
      - key: BATCH_TIMEOUT_SECONDS
        value: 3600
      - key: MAX_CONCURRENT_BATCHES
        value: 5
      - key: MAX_AUTO_PATCH_ATTEMPTS
        value: 3
      - key: OSCILLATION_PREVENTION
        value: true
      - key: AUTO_ROLLBACK
        value: true
      - key: WHITELIST_DSL_ONLY
        value: true
      - key: LOG_LEVEL
        value: INFO
      - key: LOG_FILE
        value: logs/app.log

  - type: redis
    name: redis
    plan: starter
    maxmemoryPolicy: allkeys-lru
    ipAllowList: []